import { StadiumsType } from "./stadiums";
import TEAMS, { TeamType } from "./teams";

type MatchType = {
  id: number;
  group: string;
  round: "1" | "2" | "3" | "r32" | "r16" | "qf" | "sf" | "third" | "final";
  homeTeam: TeamType; // Team or placeholder string like "1A", "Winner Match 73"
  awayTeam: TeamType;
  date: string;
  time: string;
  stadium: StadiumsType;
  // homeScore?: number;
  // awayScore?: number;
  // homePenalties?: number; // Only for knockouts
  // awayPenalties?: number; // Only for knockouts
};

const GROUP_MATCHES: MatchType[] = [
  // ── ROUND 1 ─────────────────────────────────────────────────────────────────
  // Group A — 2026-06-11
  {
    id: 1,
    group: "A",
    round: "1",
    homeTeam: TEAMS.MEX,
    awayTeam: TEAMS.RSA,
    date: "2026-06-11",
    time: "15:00",
    stadium: "Estadio Azteca",
  },
  {
    id: 2,
    group: "A",
    round: "1",
    homeTeam: TEAMS.KOR,
    awayTeam: TEAMS.CZE,
    date: "2026-06-11",
    time: "18:00",
    stadium: "Hard Rock Stadium",
  },
  // Group B — 2026-06-11
  {
    id: 3,
    group: "B",
    round: "1",
    homeTeam: TEAMS.CAN,
    awayTeam: TEAMS.BIH,
    date: "2026-06-11",
    time: "15:00",
    stadium: "MetLife Stadium",
  },
  {
    id: 4,
    group: "B",
    round: "1",
    homeTeam: TEAMS.QAT,
    awayTeam: TEAMS.SUI,
    date: "2026-06-11",
    time: "18:00",
    stadium: "Lincoln Financial Field",
  },
  // Group C — 2026-06-12
  {
    id: 5,
    group: "C",
    round: "1",
    homeTeam: TEAMS.BRA,
    awayTeam: TEAMS.MAR,
    date: "2026-06-12",
    time: "15:00",
    stadium: "SoFi Stadium",
  },
  {
    id: 6,
    group: "C",
    round: "1",
    homeTeam: TEAMS.HAI,
    awayTeam: TEAMS.SCO,
    date: "2026-06-12",
    time: "18:00",
    stadium: "Levi's Stadium",
  },
  // Group D — 2026-06-12
  {
    id: 7,
    group: "D",
    round: "1",
    homeTeam: TEAMS.USA,
    awayTeam: TEAMS.PAR,
    date: "2026-06-12",
    time: "15:00",
    stadium: "Mercedes-Benz Stadium",
  },
  {
    id: 8,
    group: "D",
    round: "1",
    homeTeam: TEAMS.AUS,
    awayTeam: TEAMS.TUR,
    date: "2026-06-12",
    time: "18:00",
    stadium: "Lumen Field",
  },
  // Group E — 2026-06-13
  {
    id: 9,
    group: "E",
    round: "1",
    homeTeam: TEAMS.GER,
    awayTeam: TEAMS.CUW,
    date: "2026-06-13",
    time: "15:00",
    stadium: "Gillette Stadium",
  },
  {
    id: 10,
    group: "E",
    round: "1",
    homeTeam: TEAMS.CIV,
    awayTeam: TEAMS.ECU,
    date: "2026-06-13",
    time: "18:00",
    stadium: "BMO Field",
  },
  // Group F — 2026-06-13
  {
    id: 11,
    group: "F",
    round: "1",
    homeTeam: TEAMS.NED,
    awayTeam: TEAMS.JPN,
    date: "2026-06-13",
    time: "15:00",
    stadium: "AT&T Stadium",
  },
  {
    id: 12,
    group: "F",
    round: "1",
    homeTeam: TEAMS.SWE,
    awayTeam: TEAMS.TUN,
    date: "2026-06-13",
    time: "18:00",
    stadium: "BC Place",
  },
  // Group G — 2026-06-14
  {
    id: 13,
    group: "G",
    round: "1",
    homeTeam: TEAMS.BEL,
    awayTeam: TEAMS.EGY,
    date: "2026-06-14",
    time: "15:00",
    stadium: "NRG Stadium",
  },
  {
    id: 14,
    group: "G",
    round: "1",
    homeTeam: TEAMS.IRN,
    awayTeam: TEAMS.NZL,
    date: "2026-06-14",
    time: "18:00",
    stadium: "Estadio AKRON",
  },
  // Group H — 2026-06-14
  {
    id: 15,
    group: "H",
    round: "1",
    homeTeam: TEAMS.ESP,
    awayTeam: TEAMS.CPV,
    date: "2026-06-14",
    time: "15:00",
    stadium: "Arrowhead Stadium",
  },
  {
    id: 16,
    group: "H",
    round: "1",
    homeTeam: TEAMS.URU,
    awayTeam: TEAMS.KSA,
    date: "2026-06-14",
    time: "18:00",
    stadium: "Estadio BBVA",
  },
  // Group I — 2026-06-15
  {
    id: 17,
    group: "I",
    round: "1",
    homeTeam: TEAMS.FRA,
    awayTeam: TEAMS.SEN,
    date: "2026-06-15",
    time: "15:00",
    stadium: "Hard Rock Stadium",
  },
  {
    id: 18,
    group: "I",
    round: "1",
    homeTeam: TEAMS.IRQ,
    awayTeam: TEAMS.NOR,
    date: "2026-06-15",
    time: "18:00",
    stadium: "Estadio Azteca",
  },
  // Group J — 2026-06-15
  {
    id: 19,
    group: "J",
    round: "1",
    homeTeam: TEAMS.ARG,
    awayTeam: TEAMS.ALG,
    date: "2026-06-15",
    time: "15:00",
    stadium: "Lincoln Financial Field",
  },
  {
    id: 20,
    group: "J",
    round: "1",
    homeTeam: TEAMS.AUT,
    awayTeam: TEAMS.JOR,
    date: "2026-06-15",
    time: "18:00",
    stadium: "MetLife Stadium",
  },
  // Group K — 2026-06-16
  {
    id: 21,
    group: "K",
    round: "1",
    homeTeam: TEAMS.POR,
    awayTeam: TEAMS.COD,
    date: "2026-06-16",
    time: "15:00",
    stadium: "Levi's Stadium",
  },
  {
    id: 22,
    group: "K",
    round: "1",
    homeTeam: TEAMS.UZB,
    awayTeam: TEAMS.COL,
    date: "2026-06-16",
    time: "18:00",
    stadium: "SoFi Stadium",
  },
  // Group L — 2026-06-16
  {
    id: 23,
    group: "L",
    round: "1",
    homeTeam: TEAMS.ENG,
    awayTeam: TEAMS.CRO,
    date: "2026-06-16",
    time: "15:00",
    stadium: "Lumen Field",
  },
  {
    id: 24,
    group: "L",
    round: "1",
    homeTeam: TEAMS.GHA,
    awayTeam: TEAMS.PAN,
    date: "2026-06-16",
    time: "18:00",
    stadium: "Mercedes-Benz Stadium",
  },

  // ── ROUND 2 ─────────────────────────────────────────────────────────────────
  // Group A — 2026-06-17
  {
    id: 25,
    group: "A",
    round: "2",
    homeTeam: TEAMS.MEX,
    awayTeam: TEAMS.KOR,
    date: "2026-06-17",
    time: "15:00",
    stadium: "Gillette Stadium",
  },
  {
    id: 26,
    group: "A",
    round: "2",
    homeTeam: TEAMS.CZE,
    awayTeam: TEAMS.RSA,
    date: "2026-06-17",
    time: "18:00",
    stadium: "BMO Field",
  },
  // Group B — 2026-06-17
  {
    id: 27,
    group: "B",
    round: "2",
    homeTeam: TEAMS.CAN,
    awayTeam: TEAMS.QAT,
    date: "2026-06-17",
    time: "15:00",
    stadium: "AT&T Stadium",
  },
  {
    id: 28,
    group: "B",
    round: "2",
    homeTeam: TEAMS.SUI,
    awayTeam: TEAMS.BIH,
    date: "2026-06-17",
    time: "18:00",
    stadium: "BC Place",
  },
  // Group C — 2026-06-18
  {
    id: 29,
    group: "C",
    round: "2",
    homeTeam: TEAMS.BRA,
    awayTeam: TEAMS.HAI,
    date: "2026-06-18",
    time: "15:00",
    stadium: "NRG Stadium",
  },
  {
    id: 30,
    group: "C",
    round: "2",
    homeTeam: TEAMS.SCO,
    awayTeam: TEAMS.MAR,
    date: "2026-06-18",
    time: "18:00",
    stadium: "Estadio AKRON",
  },
  // Group D — 2026-06-18
  {
    id: 31,
    group: "D",
    round: "2",
    homeTeam: TEAMS.USA,
    awayTeam: TEAMS.AUS,
    date: "2026-06-18",
    time: "15:00",
    stadium: "Arrowhead Stadium",
  },
  {
    id: 32,
    group: "D",
    round: "2",
    homeTeam: TEAMS.TUR,
    awayTeam: TEAMS.PAR,
    date: "2026-06-18",
    time: "18:00",
    stadium: "Estadio BBVA",
  },
  // Group E — 2026-06-19
  {
    id: 33,
    group: "E",
    round: "2",
    homeTeam: TEAMS.GER,
    awayTeam: TEAMS.CIV,
    date: "2026-06-19",
    time: "15:00",
    stadium: "Hard Rock Stadium",
  },
  {
    id: 34,
    group: "E",
    round: "2",
    homeTeam: TEAMS.ECU,
    awayTeam: TEAMS.CUW,
    date: "2026-06-19",
    time: "18:00",
    stadium: "Estadio Azteca",
  },
  // Group F — 2026-06-19
  {
    id: 35,
    group: "F",
    round: "2",
    homeTeam: TEAMS.NED,
    awayTeam: TEAMS.SWE,
    date: "2026-06-19",
    time: "15:00",
    stadium: "Lincoln Financial Field",
  },
  {
    id: 36,
    group: "F",
    round: "2",
    homeTeam: TEAMS.TUN,
    awayTeam: TEAMS.JPN,
    date: "2026-06-19",
    time: "18:00",
    stadium: "MetLife Stadium",
  },
  // Group G — 2026-06-20
  {
    id: 37,
    group: "G",
    round: "2",
    homeTeam: TEAMS.BEL,
    awayTeam: TEAMS.IRN,
    date: "2026-06-20",
    time: "15:00",
    stadium: "Levi's Stadium",
  },
  {
    id: 38,
    group: "G",
    round: "2",
    homeTeam: TEAMS.NZL,
    awayTeam: TEAMS.EGY,
    date: "2026-06-20",
    time: "18:00",
    stadium: "SoFi Stadium",
  },
  // Group H — 2026-06-20
  {
    id: 39,
    group: "H",
    round: "2",
    homeTeam: TEAMS.ESP,
    awayTeam: TEAMS.URU,
    date: "2026-06-20",
    time: "15:00",
    stadium: "Lumen Field",
  },
  {
    id: 40,
    group: "H",
    round: "2",
    homeTeam: TEAMS.KSA,
    awayTeam: TEAMS.CPV,
    date: "2026-06-20",
    time: "18:00",
    stadium: "Mercedes-Benz Stadium",
  },
  // Group I — 2026-06-21
  {
    id: 41,
    group: "I",
    round: "2",
    homeTeam: TEAMS.FRA,
    awayTeam: TEAMS.IRQ,
    date: "2026-06-21",
    time: "15:00",
    stadium: "BMO Field",
  },
  {
    id: 42,
    group: "I",
    round: "2",
    homeTeam: TEAMS.NOR,
    awayTeam: TEAMS.SEN,
    date: "2026-06-21",
    time: "18:00",
    stadium: "Gillette Stadium",
  },
  // Group J — 2026-06-21
  {
    id: 43,
    group: "J",
    round: "2",
    homeTeam: TEAMS.ARG,
    awayTeam: TEAMS.AUT,
    date: "2026-06-21",
    time: "15:00",
    stadium: "BC Place",
  },
  {
    id: 44,
    group: "J",
    round: "2",
    homeTeam: TEAMS.JOR,
    awayTeam: TEAMS.ALG,
    date: "2026-06-21",
    time: "18:00",
    stadium: "AT&T Stadium",
  },
  // Group K — 2026-06-22
  {
    id: 45,
    group: "K",
    round: "2",
    homeTeam: TEAMS.POR,
    awayTeam: TEAMS.UZB,
    date: "2026-06-22",
    time: "15:00",
    stadium: "Estadio AKRON",
  },
  {
    id: 46,
    group: "K",
    round: "2",
    homeTeam: TEAMS.COL,
    awayTeam: TEAMS.COD,
    date: "2026-06-22",
    time: "18:00",
    stadium: "NRG Stadium",
  },
  // Group L — 2026-06-22
  {
    id: 47,
    group: "L",
    round: "2",
    homeTeam: TEAMS.ENG,
    awayTeam: TEAMS.GHA,
    date: "2026-06-22",
    time: "15:00",
    stadium: "Estadio BBVA",
  },
  {
    id: 48,
    group: "L",
    round: "2",
    homeTeam: TEAMS.PAN,
    awayTeam: TEAMS.CRO,
    date: "2026-06-22",
    time: "18:00",
    stadium: "Arrowhead Stadium",
  },

  // ── ROUND 3 (simultaneous per group) ────────────────────────────────────────
  // Group A — 2026-06-23
  {
    id: 49,
    group: "A",
    round: "3",
    homeTeam: TEAMS.CZE,
    awayTeam: TEAMS.MEX,
    date: "2026-06-23",
    time: "21:00",
    stadium: "SoFi Stadium",
  },
  {
    id: 50,
    group: "A",
    round: "3",
    homeTeam: TEAMS.RSA,
    awayTeam: TEAMS.KOR,
    date: "2026-06-23",
    time: "21:00",
    stadium: "Levi's Stadium",
  },
  // Group B — 2026-06-23
  {
    id: 51,
    group: "B",
    round: "3",
    homeTeam: TEAMS.SUI,
    awayTeam: TEAMS.CAN,
    date: "2026-06-23",
    time: "21:00",
    stadium: "Mercedes-Benz Stadium",
  },
  {
    id: 52,
    group: "B",
    round: "3",
    homeTeam: TEAMS.BIH,
    awayTeam: TEAMS.QAT,
    date: "2026-06-23",
    time: "21:00",
    stadium: "Lumen Field",
  },
  // Group C — 2026-06-23
  {
    id: 53,
    group: "C",
    round: "3",
    homeTeam: TEAMS.SCO,
    awayTeam: TEAMS.BRA,
    date: "2026-06-23",
    time: "21:00",
    stadium: "Gillette Stadium",
  },
  {
    id: 54,
    group: "C",
    round: "3",
    homeTeam: TEAMS.MAR,
    awayTeam: TEAMS.HAI,
    date: "2026-06-23",
    time: "21:00",
    stadium: "BMO Field",
  },
  // Group D — 2026-06-24
  {
    id: 55,
    group: "D",
    round: "3",
    homeTeam: TEAMS.TUR,
    awayTeam: TEAMS.USA,
    date: "2026-06-24",
    time: "21:00",
    stadium: "AT&T Stadium",
  },
  {
    id: 56,
    group: "D",
    round: "3",
    homeTeam: TEAMS.PAR,
    awayTeam: TEAMS.AUS,
    date: "2026-06-24",
    time: "21:00",
    stadium: "BC Place",
  },
  // Group E — 2026-06-24
  {
    id: 57,
    group: "E",
    round: "3",
    homeTeam: TEAMS.ECU,
    awayTeam: TEAMS.GER,
    date: "2026-06-24",
    time: "21:00",
    stadium: "NRG Stadium",
  },
  {
    id: 58,
    group: "E",
    round: "3",
    homeTeam: TEAMS.CUW,
    awayTeam: TEAMS.CIV,
    date: "2026-06-24",
    time: "21:00",
    stadium: "Estadio AKRON",
  },
  // Group F — 2026-06-25
  {
    id: 59,
    group: "F",
    round: "3",
    homeTeam: TEAMS.TUN,
    awayTeam: TEAMS.NED,
    date: "2026-06-25",
    time: "21:00",
    stadium: "Arrowhead Stadium",
  },
  {
    id: 60,
    group: "F",
    round: "3",
    homeTeam: TEAMS.JPN,
    awayTeam: TEAMS.SWE,
    date: "2026-06-25",
    time: "21:00",
    stadium: "Estadio BBVA",
  },
  // Group G — 2026-06-25
  {
    id: 61,
    group: "G",
    round: "3",
    homeTeam: TEAMS.NZL,
    awayTeam: TEAMS.BEL,
    date: "2026-06-25",
    time: "21:00",
    stadium: "Hard Rock Stadium",
  },
  {
    id: 62,
    group: "G",
    round: "3",
    homeTeam: TEAMS.EGY,
    awayTeam: TEAMS.IRN,
    date: "2026-06-25",
    time: "21:00",
    stadium: "Estadio Azteca",
  },
  // Group H — 2026-06-25
  {
    id: 63,
    group: "H",
    round: "3",
    homeTeam: TEAMS.KSA,
    awayTeam: TEAMS.ESP,
    date: "2026-06-25",
    time: "21:00",
    stadium: "Lincoln Financial Field",
  },
  {
    id: 64,
    group: "H",
    round: "3",
    homeTeam: TEAMS.CPV,
    awayTeam: TEAMS.URU,
    date: "2026-06-25",
    time: "21:00",
    stadium: "MetLife Stadium",
  },
  // Group I — 2026-06-26
  {
    id: 65,
    group: "I",
    round: "3",
    homeTeam: TEAMS.NOR,
    awayTeam: TEAMS.FRA,
    date: "2026-06-26",
    time: "21:00",
    stadium: "Levi's Stadium",
  },
  {
    id: 66,
    group: "I",
    round: "3",
    homeTeam: TEAMS.SEN,
    awayTeam: TEAMS.IRQ,
    date: "2026-06-26",
    time: "21:00",
    stadium: "SoFi Stadium",
  },
  // Group J — 2026-06-26
  {
    id: 67,
    group: "J",
    round: "3",
    homeTeam: TEAMS.JOR,
    awayTeam: TEAMS.ARG,
    date: "2026-06-26",
    time: "21:00",
    stadium: "Lumen Field",
  },
  {
    id: 68,
    group: "J",
    round: "3",
    homeTeam: TEAMS.ALG,
    awayTeam: TEAMS.AUT,
    date: "2026-06-26",
    time: "21:00",
    stadium: "Mercedes-Benz Stadium",
  },
  // Group K — 2026-06-27
  {
    id: 69,
    group: "K",
    round: "3",
    homeTeam: TEAMS.COL,
    awayTeam: TEAMS.POR,
    date: "2026-06-27",
    time: "21:00",
    stadium: "BMO Field",
  },
  {
    id: 70,
    group: "K",
    round: "3",
    homeTeam: TEAMS.COD,
    awayTeam: TEAMS.UZB,
    date: "2026-06-27",
    time: "21:00",
    stadium: "Gillette Stadium",
  },
  // Group L — 2026-06-27
  {
    id: 71,
    group: "L",
    round: "3",
    homeTeam: TEAMS.PAN,
    awayTeam: TEAMS.ENG,
    date: "2026-06-27",
    time: "21:00",
    stadium: "BC Place",
  },
  {
    id: 72,
    group: "L",
    round: "3",
    homeTeam: TEAMS.CRO,
    awayTeam: TEAMS.GHA,
    date: "2026-06-27",
    time: "21:00",
    stadium: "AT&T Stadium",
  },
];

export default GROUP_MATCHES;
export type { MatchType };
